version: 2
updates:
  # Node.js dependencies
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: tuesday
      time: '02:00'
    open-pull-requests-limit: 5
    target-branch: 'develop'
    labels:
      - dependencies
      - dependabot
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      nestjs-cls:
        patterns:
          - 'nestjs-cls'
          - '@nestjs-cls/*'
